name: Delete Published Snippet

on:
  workflow_dispatch:
    inputs:
      snippet_name:
        type: string
        description: snippets/<snippet_folder_name>
        required: true

jobs:

  snippet_delete:
    name: "ğŸ—‘ï¸ Delete Published Snippet"
    runs-on: ubuntu-latest
    environment: admin

    steps:
      - name: "ğŸš§ Test input with regex"
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.inputs.snippet_name }}
          regex: '[a-z-]'

      - name: "ğŸš« Deny invalid snippet name input"
        if: ${{ steps.regex-match.outputs.match == '' }}
        run: |
          echo "Invalid snippet name input (example: my-cool-snippet)"
          exit 1

      - name: "â˜ï¸ Check out Git Repository"
        uses: actions/checkout@v2

      - name: "ğŸš§ Verify snippet exists folder"
        run: test -d ./snippets/${{ github.event.inputs.snippet_name }}/ && echo "âœ… Folder exists" || (echo âŒ Folder not found && exit 1)

      - name: "ğŸš— Move snippet folder to trash"
        run: |
          mkdir -p trash
          mkdir -p ./trash/${{ github.event.inputs.snippet_name }}
          cp -a ./snippets/${{ github.event.inputs.snippet_name }}/. ./trash/${{ github.event.inputs.snippet_name }}

      - name: "âŒ Delete the snippet folder"
        run: |
          rm -rf ./snippets/${{ github.event.inputs.snippet_name }}

      - name: "ğŸš€ Commit [${{ github.event.inputs.snippet_name }}] snippet DELETION"
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "SnippetDeleteBot"
          git config --global user.email "spencerbot@example.com"
          git commit -m "âŒ [Automated] Deleted snippet (${{ github.event.inputs.snippet_name }})"

      - name: "ğŸš€ Push changes to repo"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}